name: build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        docker build \
          -t duczen/dropbox:latest \
          .
    - name: Publish image to DockerHub
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push duczen/dropbox:latest
