name: build

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set common env vars
      run: |
        echo "IMAGE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
        echo "IMAGE_NAME=duczen/dropbox" >> $GITHUB_ENV
    - name: Build Image
      run: |
        docker build \
          -t $IMAGE_NAME:$IMAGE_TAG \
          -t $IMAGE_NAME:latest \
          .
    - name: Publish image to DockerHub
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
    - name: action-slack
      if: always()
      uses: 8398a7/action-slack@v3.8.2
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
