name: build

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set common env vars
      run: |
        echo "::set-env name=IMAGE_TAG::$(echo $GITHUB_REF | cut -d '/' -f 3)"
        echo "::set-env name=IMAGE_NAME::duczen/dropbox"
    - name: Build Image
      run: |
        docker build \
          -t $IMAGE_NAME:$IMAGE_TAG \
          -t $IMAGE_NAME:latest \
          .
    - name: Publish image to DockerHub
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
